#+TITLE: The website index (and the publisher!)
#+options: toc:nil title:nil num:nil

#+begin_export html
<div id="welcome">
<span style="font-size: 110%">
My name is <b>Ismael Khan</b>.
</span>
<br>
Welcome to my website.
</div>
#+end_export

#+begin_export html
<h4>About me</h4>
I am a Science graduate, majored in Mathematics, from the University of Queensland.

#+end_export


To start, my posts are indexed [[Posts index][here]]
  
---

/Fun fact/, this page also doubles as the same [[The machinery]["machinery"]] I use to publish it into webpage.


#+begin_export html

<style>
.my-floating-div {
position: fixed;
bottom: 0;
left: 2px;
width: 50px;
height: 35px;
background-color: rgba(0, 0, 0, 0.0); /* mostly transparent */
z-index: 9999; /* ensure it's on top */
}
</style>

<div>
<p xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/"><a property="dct:title" rel="cc:attributionURL" href="https://ismaelkhan.com">Website/Blog</a> by <a rel="cc:attributionURL dct:creator" property="cc:attributionName" href="https://ismaelkhan.com">Ismael Khan</a> is licensed under <a href="https://creativecommons.org/licenses/by-sa/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY-SA 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/sa.svg?ref=chooser-v1" alt=""></a></p>
</div>
#+end_export


#+begin_export html
<div style="height:100vh">
</div>
#+end_export

* Posts index
:PROPERTIES:
:NO_DEDICATED_PAGE: t
:END:
Before I started making this website, I tried to think about some of
the reasons for wanting to keep a blog/website.

These are what resonated with me the most:
- To learn by writing something in a way for others (you know something if you can explain it others)
- To share experiences
- To act as a "resume" (for other people, potential emplyers, potential colleagues)
- To meet new like-minded people, sharing ideas, feedback and jamming with them.
- To help people who might be experiencing a similar thing
- To inspire people

---

So with that in mind, here are my posts :)

** The journey to better barista coffee
- [[From blobs to latte art][Sun 2025-01-05: From blobs to latte art]]

** Org-mode shenanigans

** The meta-posts: how this website works
- [[The machinery][Sun 2025-01-05: The machinery]] 

#+begin_export html
<div style="height: 50vh">
</div>
#+end_export

* From blobs to latte art
[[./posts/from-blobs-to-latte-art.html][Link to narrowed page]]

Why does nothing get added from here?

* The machinery
[[./posts/the-machinery.html][Link to narrowed page]]

*Note*: this page is still a slight WIP. Though, functionally, it has
what we need for publishing into a webpage, its not explained in
depth, and there are some redundant bits of code not used in the
publication process anymore.

---

So, you have chosen to see how the sausage gets made...

Buckle up.

It's heavily inspired in design and principles to a [[https://jake-moss.com/#bootstrapping][friend of mine's website]].

The challenge that I wanted to differentiate from Jake's approach was to have a monolithic "index.org" file,
where each level one header represented a "post". Such that, from the users perspective before publishing,
the entire index.org file would be a self-contained "document" that contains all necessary instructions to
produce a functional website that is:
1. Styled using CSS
2. Structured as both...
   1. a mono-page of all posts (at /index.html), and
   2. a collection of pages that can be accessed individually (at /posts/<post-name>.html)
3. Holding all the media assets like images and videos to display (at /assets)

In this way, anyone could take the basic framework of this file, and
use it to launch a functional and good-looking website using emacs,
org-mode and the only external dependency of ~htmlize~ (for reliable
code-block syntax highlighting)

However, if no one was to ever use it apart from myself, I still think
it's a fun and interesting challenge, and an experiment in itself.

It also boasts a really simple project structure (albeit the tradeoff in
being unnecessarily simple, is that its likely a lot of "compensation"
in the form of tricks and gimmicks will have to be pulled off to get
it to play nicely)




---

I've chunked up this space into the following three steps:
1. **Initialise all necessary variables and settings** for the HTML file generation 
2. **Actually generate the HTML files** and have them go in the right spots
3. **Stage, commit and push the changes to the remote repo** so that they can be deployed to a webpage


#+RESULTS:
: org-babel-execute:css


** Style definitions
All CSS used in this website (the /stylesheet/) is also self-contained in this page.

The source block below gets evaluated, and the result is an ~org-mode~ export block,
(~#+begin_export html ... #+end_export~), that gets exported directly into this ~index.html~ file
within a ~<style>~ tag.

Hence, there is *no* ~style.css~ file, it's all here baby.

In order to display the CSS, as well as have it inserted into the HTML
file, we'll let this source block get executed with ~org-babel~.

But... css doesn't really have an ~org-babel-execute~ function. Which
makes sense, its only a markup language. But we can still leverage
~org-babel~ to achieve what we want, by making our own function.

#+BEGIN_SRC emacs-lisp
    (defun org-babel-execute:css (body params)
      "Return the BODY of the CSS block ready for a HTML webpage,
       wrapped in a <style> tag"
      (concat "<style type='text/css'>\n"
	      body
	      "</style>\n"))
#+END_SRC


#+RESULTS:
: org-babel-execute:css

Now here is the actual CSS used to style this website. But its a
little long, so I've hidden it with the option to show/hide it.

# Showing the "Show Code" & "Hide Code" buttons because the
# stylesheet displayed as a code-block is kinda looonnggg
#+begin_export html
    <style>
	.src-hideable {
	    display: none;
	}

	.src-hideable:target {
	    display: block;
	}

	.src-hideable::before {
	    content: "";
	}


    </style>

    <div style="display: flex; justify-content: space-between; align-items: center">
	<span>
	<a href="#code-block-1" class="toggle-show">Show Code, its kinda long</a>
	</span>

	<span style="margin-left: auto;">
	<a href="#!" class="toggle-show">Hide Code</a>
	</span>
    </div>
    <div id="code-block-1" class="src-hideable">
    #+end_export

#+NAME: stylesheet
#+BEGIN_SRC css :exports both :wrap export html :noweb yes 
  /* Import Merriweather font */
  @import url('https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&display=swap');

  body {
      font-family: 'Merriweather', serif;
      font-size: 11pt;
      margin: 0;
      padding: 0;
      background-color: #f8f9fa; /* Optional light background */
  }

  #welcome {
      text-align: center;
      margin-top: 20px;
  }

  .content {
      max-width: 600px; /* Centered content width */
      margin: 0 auto; /* Center the container */
      padding: 20px 5%; /* Add padding for breathing space */
  }

  /* Links */
  a {
      color: #800000; /* Maroon red */
      text-decoration: none;
  }

  a:hover {
      text-decoration: underline;
  }

  /* Responsive adjustments */
  @media (max-width: 768px) {
      .container {
	  margin: 15px;
	  padding: 15px;
      }
  }


  /* Syntax highlighting leveraging htmlize */
  .org-abbrev-table-name {
      /* abbrev-table-name */
      color: #0000ff;
  }
  .org-ansi-color-black {
      /* ansi-color-black */
      color: #000000;
      background-color: #000000;
  }
  .org-ansi-color-blue {
      /* ansi-color-blue */
      color: #0000ee;
      background-color: #0000ee;
  }
  .org-ansi-color-bold {
      /* ansi-color-bold */
      font-weight: bold;
  }
  .org-ansi-color-bright-black {
      /* ansi-color-bright-black */
      color: #4d4d4d;
      background-color: #4d4d4d;
  }
  .org-ansi-color-bright-blue {
      /* ansi-color-bright-blue */
      color: #0000ff;
      background-color: #0000ff;
  }
  .org-ansi-color-bright-cyan {
      /* ansi-color-bright-cyan */
      color: #00eeee;
      background-color: #00eeee;
  }
  .org-ansi-color-bright-green {
      /* ansi-color-bright-green */
      color: #00ee00;
      background-color: #00ee00;
  }
  .org-ansi-color-bright-magenta {
      /* ansi-color-bright-magenta */
      color: #ee00ee;
      background-color: #ee00ee;
  }
  .org-ansi-color-bright-red {
      /* ansi-color-bright-red */
      color: #ee0000;
      background-color: #ee0000;
  }
  .org-ansi-color-bright-white {
      /* ansi-color-bright-white */
      color: #ffffff;
      background-color: #ffffff;
  }
  .org-ansi-color-bright-yellow {
      /* ansi-color-bright-yellow */
      color: #eeee00;
      background-color: #eeee00;
  }
  .org-ansi-color-cyan {
      /* ansi-color-cyan */
      color: #00cdcd;
      background-color: #00cdcd;
  }
  .org-ansi-color-faint {
  }
  .org-ansi-color-fast-blink {
  }
  .org-ansi-color-green {
      /* ansi-color-green */
      color: #00cd00;
      background-color: #00cd00;
  }
  .org-ansi-color-inverse {
  }
  .org-ansi-color-italic {
      /* ansi-color-italic */
      font-style: italic;
  }
  .org-ansi-color-magenta {
      /* ansi-color-magenta */
      color: #cd00cd;
      background-color: #cd00cd;
  }
  .org-ansi-color-red {
      /* ansi-color-red */
      color: #cd0000;
      background-color: #cd0000;
  }
  .org-ansi-color-slow-blink {
  }
  .org-ansi-color-underline {
      /* ansi-color-underline */
      text-decoration: underline;
  }
  .org-ansi-color-white {
      /* ansi-color-white */
      color: #e5e5e5;
      background-color: #e5e5e5;
  }
  .org-ansi-color-yellow {
      /* ansi-color-yellow */
      color: #cdcd00;
      background-color: #cdcd00;
  }
  .org-bold {
      /* bold */
      font-weight: bold;
  }
  .org-bold-italic {
      /* bold-italic */
      font-weight: bold;
      font-style: italic;
  }
  .org-border {
  }
  .org-bracket {
  }
  .org-browse-url-button {
      /* browse-url-button */
      color: #3a5fcd;
      text-decoration: underline;
  }
  .org-buffer-menu-buffer {
      /* buffer-menu-buffer */
      font-weight: bold;
  }
  .org-builtin {
      /* font-lock-builtin-face */
      color: #483d8b;
  }
  .org-button {
      /* button */
      color: #3a5fcd;
      text-decoration: underline;
  }
  .org-calendar-month-header {
      /* calendar-month-header */
      color: #0000ff;
  }
  .org-calendar-today {
      /* calendar-today */
      text-decoration: underline;
  }
  .org-calendar-weekday-header {
      /* calendar-weekday-header */
      color: #008b8b;
  }
  .org-calendar-weekend-header {
      /* calendar-weekend-header */
      color: #b22222;
  }
  .org-child-frame-border {
  }
  .org-comint-highlight-input {
      /* comint-highlight-input */
      font-weight: bold;
  }
  .org-comint-highlight-prompt {
      /* comint-highlight-prompt */
      color: #0000cd;
  }
  .org-comment {
      /* font-lock-comment-face */
      color: #b22222;
  }
  .org-comment-delimiter {
      /* font-lock-comment-delimiter-face */
      color: #b22222;
  }
  .org-completions-common-part {
      /* completions-common-part */
      color: #0000cd;
  }
  .org-completions-first-difference {
      /* completions-first-difference */
      font-weight: bold;
  }
  .org-completions-group-separator {
      /* completions-group-separator */
      color: #7f7f7f;
      text-decoration: line-through;
  }
  .org-completions-group-title {
      /* completions-group-title */
      color: #7f7f7f;
      font-style: italic;
  }
  .org-completions-highlight {
      /* completions-highlight */
      background-color: #b4eeb4;
  }
  .org-confusingly-reordered {
      /* confusingly-reordered */
      text-decoration: underline;
  }
  .org-constant {
      /* font-lock-constant-face */
      color: #008b8b;
  }
  .org-cursor {
      /* cursor */
      background-color: #000000;
  }
  .org-delimiter {
  }
  .org-diary {
      /* diary */
      color: #ff0000;
  }
  .org-doc {
      /* font-lock-doc-face */
      color: #8b2252;
  }
  .org-doc-markup {
      /* font-lock-doc-markup-face */
      color: #008b8b;
  }
  .org-eldoc-highlight-function-argument {
      /* eldoc-highlight-function-argument */
      font-weight: bold;
  }
  .org-elisp-shorthand-font-lock {
      /* elisp-shorthand-font-lock-face */
      color: #00ffff;
  }
  .org-error {
      /* error */
      color: #ff0000;
      font-weight: bold;
  }
  .org-escape {
      /* font-lock-escape-face */
      font-weight: bold;
  }
  .org-escape-glyph {
      /* escape-glyph */
      color: #a52a2a;
  }
  .org-file-name-shadow {
      /* file-name-shadow */
      color: #7f7f7f;
  }
  .org-fill-column-indicator {
      /* fill-column-indicator */
      color: #7f7f7f;
  }
  .org-fixed-pitch {
  }
  .org-fixed-pitch-serif {
  }
  .org-fringe {
      /* fringe */
      background-color: #f2f2f2;
  }
  .org-function-call {
      /* font-lock-function-call-face */
      color: #0000ff;
  }
  .org-function-name {
      /* font-lock-function-name-face */
      color: #0000ff;
  }
  .org-glyphless-char {
      /* glyphless-char */
      font-size: 60%;
  }
  .org-header-line {
      /* header-line */
      color: #333333;
      background-color: #e5e5e5;
  }
  .org-header-line-highlight {
  }
  .org-help-argument-name {
      /* help-argument-name */
      font-style: italic;
  }
  .org-help-for-help-header {
      /* help-for-help-header */
      font-size: 126%;
  }
  .org-help-key-binding {
      /* help-key-binding */
      color: #00008b;
      background-color: #f5f5f5;
  }
  .org-highlight {
      /* highlight */
      background-color: #b4eeb4;
  }
  .org-holiday {
      /* holiday */
      background-color: #ffc0cb;
  }
  .org-homoglyph {
      /* homoglyph */
      color: #a52a2a;
  }
  .org-icon {
  }
  .org-icon-button {
      /* icon-button */
      color: #000000;
      background-color: #808080;
  }
  .org-internal-border {
  }
  .org-isearch {
      /* isearch */
      color: #b0e2ff;
      background-color: #cd00cd;
  }
  .org-isearch-fail {
      /* isearch-fail */
      background-color: #ffc1c1;
  }
  .org-isearch-group-1 {
      /* isearch-group-1 */
      color: #b0e2ff;
      background-color: #f000f0;
  }
  .org-isearch-group-2 {
      /* isearch-group-2 */
      color: #b0e2ff;
      background-color: #a000a0;
  }
  .org-italic {
      /* italic */
      font-style: italic;
  }
  .org-keyword {
      /* font-lock-keyword-face */
      color: #a020f0;
  }

  .org-css-selector {
      color: #a020f0;
  }

  .org-css-property {
      color: #0000ff;
  }
  .org-lazy-highlight {
      /* lazy-highlight */
      background-color: #afeeee;
  }
  .org-line-number-current-line {
      /* line-number-current-line */
      color: #7f7f7f;
      background-color: #ffffff;
  }
  .org-line-number-major-tick {
      /* line-number-major-tick */
      background-color: #d9d9d9;
      font-weight: bold;
  }
  .org-line-number-minor-tick {
      /* line-number-minor-tick */
      background-color: #f2f2f2;
      font-weight: bold;
  }
  .org-link {
      /* link */
      color: #3a5fcd;
      text-decoration: underline;
  }
  .org-link-visited {
      /* link-visited */
      color: #8b008b;
      text-decoration: underline;
  }
  .org-match {
      /* match */
      background-color: #fff68f;
  }
  .org-menu {
  }
  .org-minibuffer-prompt {
      /* minibuffer-prompt */
      color: #0000cd;
  }
  .org-misc-punctuation {
  }
  .org-mode-line {
      /* mode-line */
      color: #000000;
      background-color: #bfbfbf;
  }
  .org-mode-line-active {
      /* mode-line-active */
      color: #000000;
      background-color: #bfbfbf;
  }
  .org-mode-line-buffer-id {
      /* mode-line-buffer-id */
      font-weight: bold;
  }
  .org-mode-line-emphasis {
      /* mode-line-emphasis */
      font-weight: bold;
  }
  .org-mode-line-highlight {
  }
  .org-mode-line-inactive {
      /* mode-line-inactive */
      color: #333333;
      background-color: #e5e5e5;
  }
  .org-mouse {
  }
  .org-mouse-drag-and-drop-region {
      /* mouse-drag-and-drop-region */
      background-color: #eedc82;
  }
  .org-negation-char {
  }
  .org-next-error {
      /* next-error */
      background-color: #eedc82;
  }
  .org-next-error-message {
      /* next-error-message */
      background-color: #b4eeb4;
  }
  .org-nobreak-hyphen {
      /* nobreak-hyphen */
      color: #a52a2a;
  }
  .org-nobreak-space {
      /* nobreak-space */
      color: #a52a2a;
      text-decoration: underline;
  }
  .org-number {
  }
  .org-operator {
  }
  .org-org-agenda-calendar-event {
      /* org-agenda-calendar-event */
      color: #000000;
      background-color: #ffffff;
  }
  .org-org-agenda-calendar-sexp {
      /* org-agenda-calendar-sexp */
      color: #000000;
      background-color: #ffffff;
  }
  .org-org-agenda-clocking {
      /* org-agenda-clocking */
      background-color: #ffff00;
  }
  .org-org-agenda-column-dateline {
      /* org-agenda-column-dateline */
      background-color: #e5e5e5;
  }
  .org-org-agenda-current-time {
      /* org-agenda-current-time */
      color: #b8860b;
  }
  .org-org-agenda-date {
      /* org-agenda-date */
      color: #0000ff;
  }
  .org-org-agenda-date-today {
      /* org-agenda-date-today */
      color: #0000ff;
      font-weight: bold;
      font-style: italic;
  }
  .org-org-agenda-date-weekend {
      /* org-agenda-date-weekend */
      color: #0000ff;
      font-weight: bold;
  }
  .org-org-agenda-date-weekend-today {
      /* org-agenda-date-weekend-today */
      color: #0000ff;
      font-weight: bold;
      font-style: italic;
  }
  .org-org-agenda-diary {
      /* org-agenda-diary */
      color: #000000;
      background-color: #ffffff;
  }
  .org-org-agenda-dimmed-todo {
      /* org-agenda-dimmed-todo-face */
      color: #7f7f7f;
  }
  .org-org-agenda-done {
      /* org-agenda-done */
      color: #228b22;
  }
  .org-org-agenda-filter-category {
      /* org-agenda-filter-category */
      color: #000000;
      background-color: #bfbfbf;
  }
  .org-org-agenda-filter-effort {
      /* org-agenda-filter-effort */
      color: #000000;
      background-color: #bfbfbf;
  }
  .org-org-agenda-filter-regexp {
      /* org-agenda-filter-regexp */
      color: #000000;
      background-color: #bfbfbf;
  }
  .org-org-agenda-filter-tags {
      /* org-agenda-filter-tags */
      color: #000000;
      background-color: #bfbfbf;
  }
  .org-org-agenda-restriction-lock {
      /* org-agenda-restriction-lock */
      background-color: #eeeeee;
  }
  .org-org-agenda-structure {
      /* org-agenda-structure */
      color: #0000ff;
  }
  .org-org-agenda-structure-secondary {
      /* org-agenda-structure-secondary */
      color: #0000ff;
  }
  .org-org-archived {
      /* org-archived */
      color: #7f7f7f;
  }
  .org-org-block {
      /* org-block */
      color: #7f7f7f;
  }
  .org-org-block-begin-line {
      /* org-block-begin-line */
      color: #b22222;
  }
  .org-org-block-end-line {
      /* org-block-end-line */
      color: #b22222;
  }
  .org-org-checkbox {
      /* org-checkbox */
      font-weight: bold;
  }
  .org-org-checkbox-statistics-done {
      /* org-checkbox-statistics-done */
      color: #228b22;
      font-weight: bold;
  }
  .org-org-checkbox-statistics-todo {
      /* org-checkbox-statistics-todo */
      color: #ff0000;
      font-weight: bold;
  }
  .org-org-cite {
      /* org-cite */
      color: #3a5fcd;
      text-decoration: underline;
  }
  .org-org-cite-key {
      /* org-cite-key */
      color: #3a5fcd;
      text-decoration: underline;
  }
  .org-org-clock-overlay {
      /* org-clock-overlay */
      color: #000000;
      background-color: #d3d3d3;
  }
  .org-org-code {
      /* org-code */
      color: #7f7f7f;
  }
  .org-org-column {
      /* org-column */
      background-color: #e5e5e5;
  }
  .org-org-column-title {
      /* org-column-title */
      background-color: #e5e5e5;
      font-weight: bold;
      text-decoration: underline;
  }
  .org-org-date {
      /* org-date */
      color: #a020f0;
      text-decoration: underline;
  }
  .org-org-date-selected {
      /* org-date-selected */
      color: #ff0000;
  }
  .org-org-default {
      /* org-default */
      color: #000000;
      background-color: #ffffff;
  }
  .org-org-dispatcher-highlight {
      /* org-dispatcher-highlight */
      color: #00008b;
      background-color: #c6e2ff;
      font-weight: bold;
  }
  .org-org-document-info {
      /* org-document-info */
      color: #191970;
  }
  .org-org-document-info-keyword {
      /* org-document-info-keyword */
      color: #7f7f7f;
  }
  .org-org-document-title {
      /* org-document-title */
      color: #191970;
      font-weight: bold;
  }
  .org-org-done {
      /* org-done */
      color: #228b22;
      font-weight: bold;
  }
  .org-org-drawer {
      /* org-drawer */
      color: #0000ff;
  }
  .org-org-ellipsis {
      /* org-ellipsis */
      color: #b8860b;
      text-decoration: underline;
  }
  .org-org-footnote {
      /* org-footnote */
      color: #a020f0;
      text-decoration: underline;
  }
  .org-org-formula {
      /* org-formula */
      color: #b22222;
  }
  .org-org-headline-done {
      /* org-headline-done */
      color: #bc8f8f;
  }
  .org-org-headline-todo {
      /* org-headline-todo */
      color: #8b0000;
  }
  .org-org-hide {
      /* org-hide */
      color: #ffffff;
  }
  .org-org-imminent-deadline {
      /* org-imminent-deadline */
      color: #ff0000;
      font-weight: bold;
  }
  .org-org-inline-src-block {
      /* org-inline-src-block */
      color: #7f7f7f;
  }
  .org-org-latex-and-related {
      /* org-latex-and-related */
      color: #8b4513;
  }
  .org-org-level-1 {
      /* org-level-1 */
      color: #0000ff;
  }
  .org-org-level-2 {
      /* org-level-2 */
      color: #a0522d;
  }
  .org-org-level-3 {
      /* org-level-3 */
      color: #a020f0;
  }
  .org-org-level-4 {
      /* org-level-4 */
      color: #b22222;
  }
  .org-org-level-5 {
      /* org-level-5 */
      color: #228b22;
  }
  .org-org-level-6 {
      /* org-level-6 */
      color: #008b8b;
  }
  .org-org-level-7 {
      /* org-level-7 */
      color: #483d8b;
  }
  .org-org-level-8 {
      /* org-level-8 */
      color: #8b2252;
  }
  .org-org-link {
      /* org-link */
      color: #3a5fcd;
      text-decoration: underline;
  }
  .org-org-list-dt {
      /* org-list-dt */
      font-weight: bold;
  }
  .org-org-macro {
      /* org-macro */
      color: #8b4513;
  }
  .org-org-meta-line {
      /* org-meta-line */
      color: #b22222;
  }
  .org-org-mode-line-clock {
      /* org-mode-line-clock */
      color: #000000;
      background-color: #bfbfbf;
  }
  .org-org-mode-line-clock-overrun {
      /* org-mode-line-clock-overrun */
      color: #000000;
      background-color: #ff0000;
  }
  .org-org-priority {
      /* org-priority */
      color: #a020f0;
  }
  .org-org-property-value {
      /* org-property-value */
      color: #000000;
      background-color: #ffffff;
  }
  .org-org-quote {
      /* org-quote */
      color: #7f7f7f;
  }
  .org-org-scheduled {
      /* org-scheduled */
      color: #006400;
  }
  .org-org-scheduled-previously {
      /* org-scheduled-previously */
      color: #b22222;
  }
  .org-org-scheduled-today {
      /* org-scheduled-today */
      color: #006400;
  }
  .org-org-sexp-date {
      /* org-sexp-date */
      color: #a020f0;
  }
  .org-org-special-keyword {
      /* org-special-keyword */
      color: #a020f0;
  }
  .org-org-table {
      /* org-table */
      color: #0000ff;
  }
  .org-org-table-header {
      /* org-table-header */
      color: #000000;
      background-color: #d3d3d3;
  }
  .org-org-tag {
      /* org-tag */
      font-weight: bold;
  }
  .org-org-tag-group {
      /* org-tag-group */
      font-weight: bold;
  }
  .org-org-target {
      /* org-target */
      text-decoration: underline;
  }
  .org-org-time-grid {
      /* org-time-grid */
      color: #b8860b;
  }
  .org-org-todo {
      /* org-todo */
      color: #ff0000;
      font-weight: bold;
  }
  .org-org-upcoming-deadline {
      /* org-upcoming-deadline */
      color: #b22222;
  }
  .org-org-upcoming-distant-deadline {
      /* org-upcoming-distant-deadline */
      color: #000000;
      background-color: #ffffff;
  }
  .org-org-verbatim {
      /* org-verbatim */
      color: #7f7f7f;
  }
  .org-org-verse {
      /* org-verse */
      color: #7f7f7f;
  }
  .org-org-warning {
      /* org-warning */
      color: #ff0000;
      font-weight: bold;
  }
  .org-outline-1 {
      /* outline-1 */
      color: #0000ff;
  }
  .org-outline-2 {
      /* outline-2 */
      color: #a0522d;
  }
  .org-outline-3 {
      /* outline-3 */
      color: #a020f0;
  }
  .org-outline-4 {
      /* outline-4 */
      color: #b22222;
  }
  .org-outline-5 {
      /* outline-5 */
      color: #228b22;
  }
  .org-outline-6 {
      /* outline-6 */
      color: #008b8b;
  }
  .org-outline-7 {
      /* outline-7 */
      color: #483d8b;
  }
  .org-outline-8 {
      /* outline-8 */
      color: #8b2252;
  }
  .org-package-description {
      /* package-description */
      color: #000000;
      background-color: #ffffff;
  }
  .org-package-name {
      /* package-name */
      color: #3a5fcd;
      text-decoration: underline;
  }
  .org-package-status-avail-obso {
      /* package-status-avail-obso */
      color: #ff0000;
      font-weight: bold;
  }
  .org-package-status-available {
      /* package-status-available */
      color: #000000;
      background-color: #ffffff;
  }
  .org-package-status-built-in {
      /* package-status-built-in */
      color: #483d8b;
  }
  .org-package-status-dependency {
      /* package-status-dependency */
      color: #b22222;
  }
  .org-package-status-disabled {
      /* package-status-disabled */
      color: #ff0000;
      font-weight: bold;
  }
  .org-package-status-external {
      /* package-status-external */
      color: #483d8b;
  }
  .org-package-status-from-source {
  }
  .org-package-status-held {
      /* package-status-held */
      color: #008b8b;
  }
  .org-package-status-incompat {
      /* package-status-incompat */
      color: #ff0000;
      font-weight: bold;
  }
  .org-package-status-installed {
      /* package-status-installed */
      color: #b22222;
  }
  .org-package-status-unsigned {
      /* package-status-unsigned */
      color: #ff0000;
      font-weight: bold;
  }
  .org-preprocessor {
      /* font-lock-preprocessor-face */
      color: #483d8b;
  }
  .org-property-name {
      /* font-lock-property-name-face */
      color: #a0522d;
  }
  .org-property-use {
      /* font-lock-property-use-face */
      color: #a0522d;
  }
  .org-punctuation {
  }
  .org-query-replace {
      /* query-replace */
      color: #b0e2ff;
      background-color: #cd00cd;
  }
  .org-regexp {
      /* font-lock-regexp-face */
      color: #8b2252;
  }
  .org-regexp-grouping-backslash {
      /* font-lock-regexp-grouping-backslash */
      font-weight: bold;
  }
  .org-regexp-grouping-construct {
      /* font-lock-regexp-grouping-construct */
      font-weight: bold;
  }
  .org-region {
      /* region */
      background-color: #eedc82;
  }
  .org-scroll-bar {
  }
  .org-secondary-selection {
      /* secondary-selection */
      background-color: #ffff00;
  }
  .org-separator-line {
      /* separator-line */
      background-color: #a0a0a0;
      font-size: 10%;
  }
  .org-shadow {
      /* shadow */
      color: #7f7f7f;
  }
  .org-show-paren-match {
      /* show-paren-match */
      background-color: #40e0d0;
  }
  .org-show-paren-match-expression {
      /* show-paren-match-expression */
      background-color: #40e0d0;
  }
  .org-show-paren-mismatch {
      /* show-paren-mismatch */
      color: #ffffff;
      background-color: #a020f0;
  }
  .org-string {
      /* font-lock-string-face */
      color: #8b2252;
  }
  .org-success {
      /* success */
      color: #228b22;
      font-weight: bold;
  }
  .org-tab-bar {
      /* tab-bar */
      color: #000000;
      background-color: #d9d9d9;
  }
  .org-tab-bar-tab {
      /* tab-bar-tab */
      color: #000000;
      background-color: #d9d9d9;
  }
  .org-tab-bar-tab-group-current {
      /* tab-bar-tab-group-current */
      color: #000000;
      background-color: #d9d9d9;
      font-weight: bold;
  }
  .org-tab-bar-tab-inactive {
      /* tab-bar-tab-inactive */
      color: #000000;
      background-color: #bfbfbf;
  }
  .org-tab-line {
      /* tab-line */
      color: #000000;
      background-color: #d9d9d9;
      font-size: 90%;
  }
  .org-table-cell {
      /* table-cell */
      color: #e5e5e5;
      background-color: #0000ff;
  }
  .org-tabulated-list-fake-header {
      /* tabulated-list-fake-header */
      font-weight: bold;
      text-decoration: underline;
      text-decoration: overline;
  }
  .org-tool-bar {
      /* tool-bar */
      color: #000000;
      background-color: #bfbfbf;
  }
  .org-tooltip {
      /* tooltip */
      color: #000000;
      background-color: #ffffe0;
  }
  .org-trailing-whitespace {
      /* trailing-whitespace */
      background-color: #ff0000;
  }
  .org-tty-menu-disabled {
      /* tty-menu-disabled-face */
      color: #d3d3d3;
      background-color: #0000ff;
  }
  .org-tty-menu-enabled {
      /* tty-menu-enabled-face */
      color: #ffff00;
      background-color: #0000ff;
      font-weight: bold;
  }
  .org-tty-menu-selected {
      /* tty-menu-selected-face */
      background-color: #ff0000;
  }
  .org-type {
      /* font-lock-type-face */
      color: #228b22;
  }
  .org-underline {
      /* underline */
      text-decoration: underline;
  }
  .org-variable-name {
      /* font-lock-variable-name-face */
      color: #a0522d;
  }
  .org-variable-pitch {
  }
  .org-variable-pitch-text {
      /* variable-pitch-text */
      font-size: 100%;
  }
  .org-variable-use {
      /* font-lock-variable-use-face */
      color: #a0522d;
  }
  .org-vc-conflict-state {
  }
  .org-vc-edited-state {
  }
  .org-vc-locally-added-state {
  }
  .org-vc-locked-state {
  }
  .org-vc-missing-state {
  }
  .org-vc-needs-update-state {
  }
  .org-vc-removed-state {
  }
  .org-vc-state-base {
  }
  .org-vc-up-to-date-state {
  }
  .org-vertical-border {
  }
  .org-warning {
      /* warning */
      color: #ff8c00;
      font-weight: bold;
  }
  .org-warning-1 {
      /* font-lock-warning-face */
      color: #ff0000;
      font-weight: bold;
  }
  .org-window-divider {
      /* window-divider */
      color: #999999;
  }
  .org-window-divider-first-pixel {
      /* window-divider-first-pixel */
      color: #cccccc;
  }
  .org-window-divider-last-pixel {
      /* window-divider-last-pixel */
      color: #666666;
  }
#+END_SRC

#+RESULTS: stylesheet
#+begin_export html
<style type='text/css'>
/* Import Merriweather font */
@import url('https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&display=swap');

body {
    font-family: 'Merriweather', serif;
    font-size: 11pt;
    margin: 0;
    padding: 0;
    background-color: #f8f9fa; /* Optional light background */
}

#welcome {
    text-align: center;
    margin-top: 20px;
}

.content {
    max-width: 600px; /* Centered content width */
    margin: 0 auto; /* Center the container */
    padding: 20px 5%; /* Add padding for breathing space */
}

/* Links */
a {
    color: #800000; /* Maroon red */
    text-decoration: none;
}

a:hover {
    text-decoration: underline;
}

/* Responsive adjustments */
@media (max-width: 768px) {
    .container {
	margin: 15px;
	padding: 15px;
    }
}


/* Syntax highlighting leveraging htmlize */
.org-abbrev-table-name {
    /* abbrev-table-name */
    color: #0000ff;
}
.org-ansi-color-black {
    /* ansi-color-black */
    color: #000000;
    background-color: #000000;
}
.org-ansi-color-blue {
    /* ansi-color-blue */
    color: #0000ee;
    background-color: #0000ee;
}
.org-ansi-color-bold {
    /* ansi-color-bold */
    font-weight: bold;
}
.org-ansi-color-bright-black {
    /* ansi-color-bright-black */
    color: #4d4d4d;
    background-color: #4d4d4d;
}
.org-ansi-color-bright-blue {
    /* ansi-color-bright-blue */
    color: #0000ff;
    background-color: #0000ff;
}
.org-ansi-color-bright-cyan {
    /* ansi-color-bright-cyan */
    color: #00eeee;
    background-color: #00eeee;
}
.org-ansi-color-bright-green {
    /* ansi-color-bright-green */
    color: #00ee00;
    background-color: #00ee00;
}
.org-ansi-color-bright-magenta {
    /* ansi-color-bright-magenta */
    color: #ee00ee;
    background-color: #ee00ee;
}
.org-ansi-color-bright-red {
    /* ansi-color-bright-red */
    color: #ee0000;
    background-color: #ee0000;
}
.org-ansi-color-bright-white {
    /* ansi-color-bright-white */
    color: #ffffff;
    background-color: #ffffff;
}
.org-ansi-color-bright-yellow {
    /* ansi-color-bright-yellow */
    color: #eeee00;
    background-color: #eeee00;
}
.org-ansi-color-cyan {
    /* ansi-color-cyan */
    color: #00cdcd;
    background-color: #00cdcd;
}
.org-ansi-color-faint {
}
.org-ansi-color-fast-blink {
}
.org-ansi-color-green {
    /* ansi-color-green */
    color: #00cd00;
    background-color: #00cd00;
}
.org-ansi-color-inverse {
}
.org-ansi-color-italic {
    /* ansi-color-italic */
    font-style: italic;
}
.org-ansi-color-magenta {
    /* ansi-color-magenta */
    color: #cd00cd;
    background-color: #cd00cd;
}
.org-ansi-color-red {
    /* ansi-color-red */
    color: #cd0000;
    background-color: #cd0000;
}
.org-ansi-color-slow-blink {
}
.org-ansi-color-underline {
    /* ansi-color-underline */
    text-decoration: underline;
}
.org-ansi-color-white {
    /* ansi-color-white */
    color: #e5e5e5;
    background-color: #e5e5e5;
}
.org-ansi-color-yellow {
    /* ansi-color-yellow */
    color: #cdcd00;
    background-color: #cdcd00;
}
.org-bold {
    /* bold */
    font-weight: bold;
}
.org-bold-italic {
    /* bold-italic */
    font-weight: bold;
    font-style: italic;
}
.org-border {
}
.org-bracket {
}
.org-browse-url-button {
    /* browse-url-button */
    color: #3a5fcd;
    text-decoration: underline;
}
.org-buffer-menu-buffer {
    /* buffer-menu-buffer */
    font-weight: bold;
}
.org-builtin {
    /* font-lock-builtin-face */
    color: #483d8b;
}
.org-button {
    /* button */
    color: #3a5fcd;
    text-decoration: underline;
}
.org-calendar-month-header {
    /* calendar-month-header */
    color: #0000ff;
}
.org-calendar-today {
    /* calendar-today */
    text-decoration: underline;
}
.org-calendar-weekday-header {
    /* calendar-weekday-header */
    color: #008b8b;
}
.org-calendar-weekend-header {
    /* calendar-weekend-header */
    color: #b22222;
}
.org-child-frame-border {
}
.org-comint-highlight-input {
    /* comint-highlight-input */
    font-weight: bold;
}
.org-comint-highlight-prompt {
    /* comint-highlight-prompt */
    color: #0000cd;
}
.org-comment {
    /* font-lock-comment-face */
    color: #b22222;
}
.org-comment-delimiter {
    /* font-lock-comment-delimiter-face */
    color: #b22222;
}
.org-completions-common-part {
    /* completions-common-part */
    color: #0000cd;
}
.org-completions-first-difference {
    /* completions-first-difference */
    font-weight: bold;
}
.org-completions-group-separator {
    /* completions-group-separator */
    color: #7f7f7f;
    text-decoration: line-through;
}
.org-completions-group-title {
    /* completions-group-title */
    color: #7f7f7f;
    font-style: italic;
}
.org-completions-highlight {
    /* completions-highlight */
    background-color: #b4eeb4;
}
.org-confusingly-reordered {
    /* confusingly-reordered */
    text-decoration: underline;
}
.org-constant {
    /* font-lock-constant-face */
    color: #008b8b;
}
.org-cursor {
    /* cursor */
    background-color: #000000;
}
.org-delimiter {
}
.org-diary {
    /* diary */
    color: #ff0000;
}
.org-doc {
    /* font-lock-doc-face */
    color: #8b2252;
}
.org-doc-markup {
    /* font-lock-doc-markup-face */
    color: #008b8b;
}
.org-eldoc-highlight-function-argument {
    /* eldoc-highlight-function-argument */
    font-weight: bold;
}
.org-elisp-shorthand-font-lock {
    /* elisp-shorthand-font-lock-face */
    color: #00ffff;
}
.org-error {
    /* error */
    color: #ff0000;
    font-weight: bold;
}
.org-escape {
    /* font-lock-escape-face */
    font-weight: bold;
}
.org-escape-glyph {
    /* escape-glyph */
    color: #a52a2a;
}
.org-file-name-shadow {
    /* file-name-shadow */
    color: #7f7f7f;
}
.org-fill-column-indicator {
    /* fill-column-indicator */
    color: #7f7f7f;
}
.org-fixed-pitch {
}
.org-fixed-pitch-serif {
}
.org-fringe {
    /* fringe */
    background-color: #f2f2f2;
}
.org-function-call {
    /* font-lock-function-call-face */
    color: #0000ff;
}
.org-function-name {
    /* font-lock-function-name-face */
    color: #0000ff;
}
.org-glyphless-char {
    /* glyphless-char */
    font-size: 60%;
}
.org-header-line {
    /* header-line */
    color: #333333;
    background-color: #e5e5e5;
}
.org-header-line-highlight {
}
.org-help-argument-name {
    /* help-argument-name */
    font-style: italic;
}
.org-help-for-help-header {
    /* help-for-help-header */
    font-size: 126%;
}
.org-help-key-binding {
    /* help-key-binding */
    color: #00008b;
    background-color: #f5f5f5;
}
.org-highlight {
    /* highlight */
    background-color: #b4eeb4;
}
.org-holiday {
    /* holiday */
    background-color: #ffc0cb;
}
.org-homoglyph {
    /* homoglyph */
    color: #a52a2a;
}
.org-icon {
}
.org-icon-button {
    /* icon-button */
    color: #000000;
    background-color: #808080;
}
.org-internal-border {
}
.org-isearch {
    /* isearch */
    color: #b0e2ff;
    background-color: #cd00cd;
}
.org-isearch-fail {
    /* isearch-fail */
    background-color: #ffc1c1;
}
.org-isearch-group-1 {
    /* isearch-group-1 */
    color: #b0e2ff;
    background-color: #f000f0;
}
.org-isearch-group-2 {
    /* isearch-group-2 */
    color: #b0e2ff;
    background-color: #a000a0;
}
.org-italic {
    /* italic */
    font-style: italic;
}
.org-keyword {
    /* font-lock-keyword-face */
    color: #a020f0;
}

.org-css-selector {
    color: #a020f0;
}

.org-css-property {
    color: #0000ff;
}
.org-lazy-highlight {
    /* lazy-highlight */
    background-color: #afeeee;
}
.org-line-number-current-line {
    /* line-number-current-line */
    color: #7f7f7f;
    background-color: #ffffff;
}
.org-line-number-major-tick {
    /* line-number-major-tick */
    background-color: #d9d9d9;
    font-weight: bold;
}
.org-line-number-minor-tick {
    /* line-number-minor-tick */
    background-color: #f2f2f2;
    font-weight: bold;
}
.org-link {
    /* link */
    color: #3a5fcd;
    text-decoration: underline;
}
.org-link-visited {
    /* link-visited */
    color: #8b008b;
    text-decoration: underline;
}
.org-match {
    /* match */
    background-color: #fff68f;
}
.org-menu {
}
.org-minibuffer-prompt {
    /* minibuffer-prompt */
    color: #0000cd;
}
.org-misc-punctuation {
}
.org-mode-line {
    /* mode-line */
    color: #000000;
    background-color: #bfbfbf;
}
.org-mode-line-active {
    /* mode-line-active */
    color: #000000;
    background-color: #bfbfbf;
}
.org-mode-line-buffer-id {
    /* mode-line-buffer-id */
    font-weight: bold;
}
.org-mode-line-emphasis {
    /* mode-line-emphasis */
    font-weight: bold;
}
.org-mode-line-highlight {
}
.org-mode-line-inactive {
    /* mode-line-inactive */
    color: #333333;
    background-color: #e5e5e5;
}
.org-mouse {
}
.org-mouse-drag-and-drop-region {
    /* mouse-drag-and-drop-region */
    background-color: #eedc82;
}
.org-negation-char {
}
.org-next-error {
    /* next-error */
    background-color: #eedc82;
}
.org-next-error-message {
    /* next-error-message */
    background-color: #b4eeb4;
}
.org-nobreak-hyphen {
    /* nobreak-hyphen */
    color: #a52a2a;
}
.org-nobreak-space {
    /* nobreak-space */
    color: #a52a2a;
    text-decoration: underline;
}
.org-number {
}
.org-operator {
}
.org-org-agenda-calendar-event {
    /* org-agenda-calendar-event */
    color: #000000;
    background-color: #ffffff;
}
.org-org-agenda-calendar-sexp {
    /* org-agenda-calendar-sexp */
    color: #000000;
    background-color: #ffffff;
}
.org-org-agenda-clocking {
    /* org-agenda-clocking */
    background-color: #ffff00;
}
.org-org-agenda-column-dateline {
    /* org-agenda-column-dateline */
    background-color: #e5e5e5;
}
.org-org-agenda-current-time {
    /* org-agenda-current-time */
    color: #b8860b;
}
.org-org-agenda-date {
    /* org-agenda-date */
    color: #0000ff;
}
.org-org-agenda-date-today {
    /* org-agenda-date-today */
    color: #0000ff;
    font-weight: bold;
    font-style: italic;
}
.org-org-agenda-date-weekend {
    /* org-agenda-date-weekend */
    color: #0000ff;
    font-weight: bold;
}
.org-org-agenda-date-weekend-today {
    /* org-agenda-date-weekend-today */
    color: #0000ff;
    font-weight: bold;
    font-style: italic;
}
.org-org-agenda-diary {
    /* org-agenda-diary */
    color: #000000;
    background-color: #ffffff;
}
.org-org-agenda-dimmed-todo {
    /* org-agenda-dimmed-todo-face */
    color: #7f7f7f;
}
.org-org-agenda-done {
    /* org-agenda-done */
    color: #228b22;
}
.org-org-agenda-filter-category {
    /* org-agenda-filter-category */
    color: #000000;
    background-color: #bfbfbf;
}
.org-org-agenda-filter-effort {
    /* org-agenda-filter-effort */
    color: #000000;
    background-color: #bfbfbf;
}
.org-org-agenda-filter-regexp {
    /* org-agenda-filter-regexp */
    color: #000000;
    background-color: #bfbfbf;
}
.org-org-agenda-filter-tags {
    /* org-agenda-filter-tags */
    color: #000000;
    background-color: #bfbfbf;
}
.org-org-agenda-restriction-lock {
    /* org-agenda-restriction-lock */
    background-color: #eeeeee;
}
.org-org-agenda-structure {
    /* org-agenda-structure */
    color: #0000ff;
}
.org-org-agenda-structure-secondary {
    /* org-agenda-structure-secondary */
    color: #0000ff;
}
.org-org-archived {
    /* org-archived */
    color: #7f7f7f;
}
.org-org-block {
    /* org-block */
    color: #7f7f7f;
}
.org-org-block-begin-line {
    /* org-block-begin-line */
    color: #b22222;
}
.org-org-block-end-line {
    /* org-block-end-line */
    color: #b22222;
}
.org-org-checkbox {
    /* org-checkbox */
    font-weight: bold;
}
.org-org-checkbox-statistics-done {
    /* org-checkbox-statistics-done */
    color: #228b22;
    font-weight: bold;
}
.org-org-checkbox-statistics-todo {
    /* org-checkbox-statistics-todo */
    color: #ff0000;
    font-weight: bold;
}
.org-org-cite {
    /* org-cite */
    color: #3a5fcd;
    text-decoration: underline;
}
.org-org-cite-key {
    /* org-cite-key */
    color: #3a5fcd;
    text-decoration: underline;
}
.org-org-clock-overlay {
    /* org-clock-overlay */
    color: #000000;
    background-color: #d3d3d3;
}
.org-org-code {
    /* org-code */
    color: #7f7f7f;
}
.org-org-column {
    /* org-column */
    background-color: #e5e5e5;
}
.org-org-column-title {
    /* org-column-title */
    background-color: #e5e5e5;
    font-weight: bold;
    text-decoration: underline;
}
.org-org-date {
    /* org-date */
    color: #a020f0;
    text-decoration: underline;
}
.org-org-date-selected {
    /* org-date-selected */
    color: #ff0000;
}
.org-org-default {
    /* org-default */
    color: #000000;
    background-color: #ffffff;
}
.org-org-dispatcher-highlight {
    /* org-dispatcher-highlight */
    color: #00008b;
    background-color: #c6e2ff;
    font-weight: bold;
}
.org-org-document-info {
    /* org-document-info */
    color: #191970;
}
.org-org-document-info-keyword {
    /* org-document-info-keyword */
    color: #7f7f7f;
}
.org-org-document-title {
    /* org-document-title */
    color: #191970;
    font-weight: bold;
}
.org-org-done {
    /* org-done */
    color: #228b22;
    font-weight: bold;
}
.org-org-drawer {
    /* org-drawer */
    color: #0000ff;
}
.org-org-ellipsis {
    /* org-ellipsis */
    color: #b8860b;
    text-decoration: underline;
}
.org-org-footnote {
    /* org-footnote */
    color: #a020f0;
    text-decoration: underline;
}
.org-org-formula {
    /* org-formula */
    color: #b22222;
}
.org-org-headline-done {
    /* org-headline-done */
    color: #bc8f8f;
}
.org-org-headline-todo {
    /* org-headline-todo */
    color: #8b0000;
}
.org-org-hide {
    /* org-hide */
    color: #ffffff;
}
.org-org-imminent-deadline {
    /* org-imminent-deadline */
    color: #ff0000;
    font-weight: bold;
}
.org-org-inline-src-block {
    /* org-inline-src-block */
    color: #7f7f7f;
}
.org-org-latex-and-related {
    /* org-latex-and-related */
    color: #8b4513;
}
.org-org-level-1 {
    /* org-level-1 */
    color: #0000ff;
}
.org-org-level-2 {
    /* org-level-2 */
    color: #a0522d;
}
.org-org-level-3 {
    /* org-level-3 */
    color: #a020f0;
}
.org-org-level-4 {
    /* org-level-4 */
    color: #b22222;
}
.org-org-level-5 {
    /* org-level-5 */
    color: #228b22;
}
.org-org-level-6 {
    /* org-level-6 */
    color: #008b8b;
}
.org-org-level-7 {
    /* org-level-7 */
    color: #483d8b;
}
.org-org-level-8 {
    /* org-level-8 */
    color: #8b2252;
}
.org-org-link {
    /* org-link */
    color: #3a5fcd;
    text-decoration: underline;
}
.org-org-list-dt {
    /* org-list-dt */
    font-weight: bold;
}
.org-org-macro {
    /* org-macro */
    color: #8b4513;
}
.org-org-meta-line {
    /* org-meta-line */
    color: #b22222;
}
.org-org-mode-line-clock {
    /* org-mode-line-clock */
    color: #000000;
    background-color: #bfbfbf;
}
.org-org-mode-line-clock-overrun {
    /* org-mode-line-clock-overrun */
    color: #000000;
    background-color: #ff0000;
}
.org-org-priority {
    /* org-priority */
    color: #a020f0;
}
.org-org-property-value {
    /* org-property-value */
    color: #000000;
    background-color: #ffffff;
}
.org-org-quote {
    /* org-quote */
    color: #7f7f7f;
}
.org-org-scheduled {
    /* org-scheduled */
    color: #006400;
}
.org-org-scheduled-previously {
    /* org-scheduled-previously */
    color: #b22222;
}
.org-org-scheduled-today {
    /* org-scheduled-today */
    color: #006400;
}
.org-org-sexp-date {
    /* org-sexp-date */
    color: #a020f0;
}
.org-org-special-keyword {
    /* org-special-keyword */
    color: #a020f0;
}
.org-org-table {
    /* org-table */
    color: #0000ff;
}
.org-org-table-header {
    /* org-table-header */
    color: #000000;
    background-color: #d3d3d3;
}
.org-org-tag {
    /* org-tag */
    font-weight: bold;
}
.org-org-tag-group {
    /* org-tag-group */
    font-weight: bold;
}
.org-org-target {
    /* org-target */
    text-decoration: underline;
}
.org-org-time-grid {
    /* org-time-grid */
    color: #b8860b;
}
.org-org-todo {
    /* org-todo */
    color: #ff0000;
    font-weight: bold;
}
.org-org-upcoming-deadline {
    /* org-upcoming-deadline */
    color: #b22222;
}
.org-org-upcoming-distant-deadline {
    /* org-upcoming-distant-deadline */
    color: #000000;
    background-color: #ffffff;
}
.org-org-verbatim {
    /* org-verbatim */
    color: #7f7f7f;
}
.org-org-verse {
    /* org-verse */
    color: #7f7f7f;
}
.org-org-warning {
    /* org-warning */
    color: #ff0000;
    font-weight: bold;
}
.org-outline-1 {
    /* outline-1 */
    color: #0000ff;
}
.org-outline-2 {
    /* outline-2 */
    color: #a0522d;
}
.org-outline-3 {
    /* outline-3 */
    color: #a020f0;
}
.org-outline-4 {
    /* outline-4 */
    color: #b22222;
}
.org-outline-5 {
    /* outline-5 */
    color: #228b22;
}
.org-outline-6 {
    /* outline-6 */
    color: #008b8b;
}
.org-outline-7 {
    /* outline-7 */
    color: #483d8b;
}
.org-outline-8 {
    /* outline-8 */
    color: #8b2252;
}
.org-package-description {
    /* package-description */
    color: #000000;
    background-color: #ffffff;
}
.org-package-name {
    /* package-name */
    color: #3a5fcd;
    text-decoration: underline;
}
.org-package-status-avail-obso {
    /* package-status-avail-obso */
    color: #ff0000;
    font-weight: bold;
}
.org-package-status-available {
    /* package-status-available */
    color: #000000;
    background-color: #ffffff;
}
.org-package-status-built-in {
    /* package-status-built-in */
    color: #483d8b;
}
.org-package-status-dependency {
    /* package-status-dependency */
    color: #b22222;
}
.org-package-status-disabled {
    /* package-status-disabled */
    color: #ff0000;
    font-weight: bold;
}
.org-package-status-external {
    /* package-status-external */
    color: #483d8b;
}
.org-package-status-from-source {
}
.org-package-status-held {
    /* package-status-held */
    color: #008b8b;
}
.org-package-status-incompat {
    /* package-status-incompat */
    color: #ff0000;
    font-weight: bold;
}
.org-package-status-installed {
    /* package-status-installed */
    color: #b22222;
}
.org-package-status-unsigned {
    /* package-status-unsigned */
    color: #ff0000;
    font-weight: bold;
}
.org-preprocessor {
    /* font-lock-preprocessor-face */
    color: #483d8b;
}
.org-property-name {
    /* font-lock-property-name-face */
    color: #a0522d;
}
.org-property-use {
    /* font-lock-property-use-face */
    color: #a0522d;
}
.org-punctuation {
}
.org-query-replace {
    /* query-replace */
    color: #b0e2ff;
    background-color: #cd00cd;
}
.org-regexp {
    /* font-lock-regexp-face */
    color: #8b2252;
}
.org-regexp-grouping-backslash {
    /* font-lock-regexp-grouping-backslash */
    font-weight: bold;
}
.org-regexp-grouping-construct {
    /* font-lock-regexp-grouping-construct */
    font-weight: bold;
}
.org-region {
    /* region */
    background-color: #eedc82;
}
.org-scroll-bar {
}
.org-secondary-selection {
    /* secondary-selection */
    background-color: #ffff00;
}
.org-separator-line {
    /* separator-line */
    background-color: #a0a0a0;
    font-size: 10%;
}
.org-shadow {
    /* shadow */
    color: #7f7f7f;
}
.org-show-paren-match {
    /* show-paren-match */
    background-color: #40e0d0;
}
.org-show-paren-match-expression {
    /* show-paren-match-expression */
    background-color: #40e0d0;
}
.org-show-paren-mismatch {
    /* show-paren-mismatch */
    color: #ffffff;
    background-color: #a020f0;
}
.org-string {
    /* font-lock-string-face */
    color: #8b2252;
}
.org-success {
    /* success */
    color: #228b22;
    font-weight: bold;
}
.org-tab-bar {
    /* tab-bar */
    color: #000000;
    background-color: #d9d9d9;
}
.org-tab-bar-tab {
    /* tab-bar-tab */
    color: #000000;
    background-color: #d9d9d9;
}
.org-tab-bar-tab-group-current {
    /* tab-bar-tab-group-current */
    color: #000000;
    background-color: #d9d9d9;
    font-weight: bold;
}
.org-tab-bar-tab-inactive {
    /* tab-bar-tab-inactive */
    color: #000000;
    background-color: #bfbfbf;
}
.org-tab-line {
    /* tab-line */
    color: #000000;
    background-color: #d9d9d9;
    font-size: 90%;
}
.org-table-cell {
    /* table-cell */
    color: #e5e5e5;
    background-color: #0000ff;
}
.org-tabulated-list-fake-header {
    /* tabulated-list-fake-header */
    font-weight: bold;
    text-decoration: underline;
    text-decoration: overline;
}
.org-tool-bar {
    /* tool-bar */
    color: #000000;
    background-color: #bfbfbf;
}
.org-tooltip {
    /* tooltip */
    color: #000000;
    background-color: #ffffe0;
}
.org-trailing-whitespace {
    /* trailing-whitespace */
    background-color: #ff0000;
}
.org-tty-menu-disabled {
    /* tty-menu-disabled-face */
    color: #d3d3d3;
    background-color: #0000ff;
}
.org-tty-menu-enabled {
    /* tty-menu-enabled-face */
    color: #ffff00;
    background-color: #0000ff;
    font-weight: bold;
}
.org-tty-menu-selected {
    /* tty-menu-selected-face */
    background-color: #ff0000;
}
.org-type {
    /* font-lock-type-face */
    color: #228b22;
}
.org-underline {
    /* underline */
    text-decoration: underline;
}
.org-variable-name {
    /* font-lock-variable-name-face */
    color: #a0522d;
}
.org-variable-pitch {
}
.org-variable-pitch-text {
    /* variable-pitch-text */
    font-size: 100%;
}
.org-variable-use {
    /* font-lock-variable-use-face */
    color: #a0522d;
}
.org-vc-conflict-state {
}
.org-vc-edited-state {
}
.org-vc-locally-added-state {
}
.org-vc-locked-state {
}
.org-vc-missing-state {
}
.org-vc-needs-update-state {
}
.org-vc-removed-state {
}
.org-vc-state-base {
}
.org-vc-up-to-date-state {
}
.org-vertical-border {
}
.org-warning {
    /* warning */
    color: #ff8c00;
    font-weight: bold;
}
.org-warning-1 {
    /* font-lock-warning-face */
    color: #ff0000;
    font-weight: bold;
}
.org-window-divider {
    /* window-divider */
    color: #999999;
}
.org-window-divider-first-pixel {
    /* window-divider-first-pixel */
    color: #cccccc;
}
.org-window-divider-last-pixel {
    /* window-divider-last-pixel */
    color: #666666;
}</style>
#+end_export

#+RESULTS:
#+begin_export html 
<style type='text/css'>
/* Import Merriweather font */
@import url('https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&display=swap');

body {
    font-family: 'Merriweather', serif;
    font-size: 11pt;
    margin: 0;
    padding: 0;
    background-color: #f8f9fa; /* Optional light background */
}

#welcome {
    text-align: center;
    margin-top: 20px;
}

.content {
    max-width: 600px; /* Centered content width */
    margin: 0 auto; /* Center the container */
    padding: 20px 5%; /* Add padding for breathing space */
}

/* Links */
a {
    color: #800000; /* Maroon red */
    text-decoration: none;
}

a:hover {
    text-decoration: underline;
}

/* Responsive adjustments */
@media (max-width: 768px) {
    .container {
	margin: 15px;
	padding: 15px;
    }
}


/* Syntax highlighting leveraging htmlize */
.org-abbrev-table-name {
    /* abbrev-table-name */
    color: #0000ff;
}
.org-ansi-color-black {
    /* ansi-color-black */
    color: #000000;
    background-color: #000000;
}
.org-ansi-color-blue {
    /* ansi-color-blue */
    color: #0000ee;
    background-color: #0000ee;
}
.org-ansi-color-bold {
    /* ansi-color-bold */
    font-weight: bold;
}
.org-ansi-color-bright-black {
    /* ansi-color-bright-black */
    color: #4d4d4d;
    background-color: #4d4d4d;
}
.org-ansi-color-bright-blue {
    /* ansi-color-bright-blue */
    color: #0000ff;
    background-color: #0000ff;
}
.org-ansi-color-bright-cyan {
    /* ansi-color-bright-cyan */
    color: #00eeee;
    background-color: #00eeee;
}
.org-ansi-color-bright-green {
    /* ansi-color-bright-green */
    color: #00ee00;
    background-color: #00ee00;
}
.org-ansi-color-bright-magenta {
    /* ansi-color-bright-magenta */
    color: #ee00ee;
    background-color: #ee00ee;
}
.org-ansi-color-bright-red {
    /* ansi-color-bright-red */
    color: #ee0000;
    background-color: #ee0000;
}
.org-ansi-color-bright-white {
    /* ansi-color-bright-white */
    color: #ffffff;
    background-color: #ffffff;
}
.org-ansi-color-bright-yellow {
    /* ansi-color-bright-yellow */
    color: #eeee00;
    background-color: #eeee00;
}
.org-ansi-color-cyan {
    /* ansi-color-cyan */
    color: #00cdcd;
    background-color: #00cdcd;
}
.org-ansi-color-faint {
}
.org-ansi-color-fast-blink {
}
.org-ansi-color-green {
    /* ansi-color-green */
    color: #00cd00;
    background-color: #00cd00;
}
.org-ansi-color-inverse {
}
.org-ansi-color-italic {
    /* ansi-color-italic */
    font-style: italic;
}
.org-ansi-color-magenta {
    /* ansi-color-magenta */
    color: #cd00cd;
    background-color: #cd00cd;
}
.org-ansi-color-red {
    /* ansi-color-red */
    color: #cd0000;
    background-color: #cd0000;
}
.org-ansi-color-slow-blink {
}
.org-ansi-color-underline {
    /* ansi-color-underline */
    text-decoration: underline;
}
.org-ansi-color-white {
    /* ansi-color-white */
    color: #e5e5e5;
    background-color: #e5e5e5;
}
.org-ansi-color-yellow {
    /* ansi-color-yellow */
    color: #cdcd00;
    background-color: #cdcd00;
}
.org-bold {
    /* bold */
    font-weight: bold;
}
.org-bold-italic {
    /* bold-italic */
    font-weight: bold;
    font-style: italic;
}
.org-border {
}
.org-bracket {
}
.org-browse-url-button {
    /* browse-url-button */
    color: #3a5fcd;
    text-decoration: underline;
}
.org-buffer-menu-buffer {
    /* buffer-menu-buffer */
    font-weight: bold;
}
.org-builtin {
    /* font-lock-builtin-face */
    color: #483d8b;
}
.org-button {
    /* button */
    color: #3a5fcd;
    text-decoration: underline;
}
.org-calendar-month-header {
    /* calendar-month-header */
    color: #0000ff;
}
.org-calendar-today {
    /* calendar-today */
    text-decoration: underline;
}
.org-calendar-weekday-header {
    /* calendar-weekday-header */
    color: #008b8b;
}
.org-calendar-weekend-header {
    /* calendar-weekend-header */
    color: #b22222;
}
.org-child-frame-border {
}
.org-comint-highlight-input {
    /* comint-highlight-input */
    font-weight: bold;
}
.org-comint-highlight-prompt {
    /* comint-highlight-prompt */
    color: #0000cd;
}
.org-comment {
    /* font-lock-comment-face */
    color: #b22222;
}
.org-comment-delimiter {
    /* font-lock-comment-delimiter-face */
    color: #b22222;
}
.org-completions-common-part {
    /* completions-common-part */
    color: #0000cd;
}
.org-completions-first-difference {
    /* completions-first-difference */
    font-weight: bold;
}
.org-completions-group-separator {
    /* completions-group-separator */
    color: #7f7f7f;
    text-decoration: line-through;
}
.org-completions-group-title {
    /* completions-group-title */
    color: #7f7f7f;
    font-style: italic;
}
.org-completions-highlight {
    /* completions-highlight */
    background-color: #b4eeb4;
}
.org-confusingly-reordered {
    /* confusingly-reordered */
    text-decoration: underline;
}
.org-constant {
    /* font-lock-constant-face */
    color: #008b8b;
}
.org-cursor {
    /* cursor */
    background-color: #000000;
}
.org-delimiter {
}
.org-diary {
    /* diary */
    color: #ff0000;
}
.org-doc {
    /* font-lock-doc-face */
    color: #8b2252;
}
.org-doc-markup {
    /* font-lock-doc-markup-face */
    color: #008b8b;
}
.org-eldoc-highlight-function-argument {
    /* eldoc-highlight-function-argument */
    font-weight: bold;
}
.org-elisp-shorthand-font-lock {
    /* elisp-shorthand-font-lock-face */
    color: #00ffff;
}
.org-error {
    /* error */
    color: #ff0000;
    font-weight: bold;
}
.org-escape {
    /* font-lock-escape-face */
    font-weight: bold;
}
.org-escape-glyph {
    /* escape-glyph */
    color: #a52a2a;
}
.org-file-name-shadow {
    /* file-name-shadow */
    color: #7f7f7f;
}
.org-fill-column-indicator {
    /* fill-column-indicator */
    color: #7f7f7f;
}
.org-fixed-pitch {
}
.org-fixed-pitch-serif {
}
.org-fringe {
    /* fringe */
    background-color: #f2f2f2;
}
.org-function-call {
    /* font-lock-function-call-face */
    color: #0000ff;
}
.org-function-name {
    /* font-lock-function-name-face */
    color: #0000ff;
}
.org-glyphless-char {
    /* glyphless-char */
    font-size: 60%;
}
.org-header-line {
    /* header-line */
    color: #333333;
    background-color: #e5e5e5;
}
.org-header-line-highlight {
}
.org-help-argument-name {
    /* help-argument-name */
    font-style: italic;
}
.org-help-for-help-header {
    /* help-for-help-header */
    font-size: 126%;
}
.org-help-key-binding {
    /* help-key-binding */
    color: #00008b;
    background-color: #f5f5f5;
}
.org-highlight {
    /* highlight */
    background-color: #b4eeb4;
}
.org-holiday {
    /* holiday */
    background-color: #ffc0cb;
}
.org-homoglyph {
    /* homoglyph */
    color: #a52a2a;
}
.org-icon {
}
.org-icon-button {
    /* icon-button */
    color: #000000;
    background-color: #808080;
}
.org-internal-border {
}
.org-isearch {
    /* isearch */
    color: #b0e2ff;
    background-color: #cd00cd;
}
.org-isearch-fail {
    /* isearch-fail */
    background-color: #ffc1c1;
}
.org-isearch-group-1 {
    /* isearch-group-1 */
    color: #b0e2ff;
    background-color: #f000f0;
}
.org-isearch-group-2 {
    /* isearch-group-2 */
    color: #b0e2ff;
    background-color: #a000a0;
}
.org-italic {
    /* italic */
    font-style: italic;
}
.org-keyword {
    /* font-lock-keyword-face */
    color: #a020f0;
}

.org-css-selector {
    color: #a020f0;
}

.org-css-property {
    color: #0000ff;
}
.org-lazy-highlight {
    /* lazy-highlight */
    background-color: #afeeee;
}
.org-line-number-current-line {
    /* line-number-current-line */
    color: #7f7f7f;
    background-color: #ffffff;
}
.org-line-number-major-tick {
    /* line-number-major-tick */
    background-color: #d9d9d9;
    font-weight: bold;
}
.org-line-number-minor-tick {
    /* line-number-minor-tick */
    background-color: #f2f2f2;
    font-weight: bold;
}
.org-link {
    /* link */
    color: #3a5fcd;
    text-decoration: underline;
}
.org-link-visited {
    /* link-visited */
    color: #8b008b;
    text-decoration: underline;
}
.org-match {
    /* match */
    background-color: #fff68f;
}
.org-menu {
}
.org-minibuffer-prompt {
    /* minibuffer-prompt */
    color: #0000cd;
}
.org-misc-punctuation {
}
.org-mode-line {
    /* mode-line */
    color: #000000;
    background-color: #bfbfbf;
}
.org-mode-line-active {
    /* mode-line-active */
    color: #000000;
    background-color: #bfbfbf;
}
.org-mode-line-buffer-id {
    /* mode-line-buffer-id */
    font-weight: bold;
}
.org-mode-line-emphasis {
    /* mode-line-emphasis */
    font-weight: bold;
}
.org-mode-line-highlight {
}
.org-mode-line-inactive {
    /* mode-line-inactive */
    color: #333333;
    background-color: #e5e5e5;
}
.org-mouse {
}
.org-mouse-drag-and-drop-region {
    /* mouse-drag-and-drop-region */
    background-color: #eedc82;
}
.org-negation-char {
}
.org-next-error {
    /* next-error */
    background-color: #eedc82;
}
.org-next-error-message {
    /* next-error-message */
    background-color: #b4eeb4;
}
.org-nobreak-hyphen {
    /* nobreak-hyphen */
    color: #a52a2a;
}
.org-nobreak-space {
    /* nobreak-space */
    color: #a52a2a;
    text-decoration: underline;
}
.org-number {
}
.org-operator {
}
.org-org-agenda-calendar-event {
    /* org-agenda-calendar-event */
    color: #000000;
    background-color: #ffffff;
}
.org-org-agenda-calendar-sexp {
    /* org-agenda-calendar-sexp */
    color: #000000;
    background-color: #ffffff;
}
.org-org-agenda-clocking {
    /* org-agenda-clocking */
    background-color: #ffff00;
}
.org-org-agenda-column-dateline {
    /* org-agenda-column-dateline */
    background-color: #e5e5e5;
}
.org-org-agenda-current-time {
    /* org-agenda-current-time */
    color: #b8860b;
}
.org-org-agenda-date {
    /* org-agenda-date */
    color: #0000ff;
}
.org-org-agenda-date-today {
    /* org-agenda-date-today */
    color: #0000ff;
    font-weight: bold;
    font-style: italic;
}
.org-org-agenda-date-weekend {
    /* org-agenda-date-weekend */
    color: #0000ff;
    font-weight: bold;
}
.org-org-agenda-date-weekend-today {
    /* org-agenda-date-weekend-today */
    color: #0000ff;
    font-weight: bold;
    font-style: italic;
}
.org-org-agenda-diary {
    /* org-agenda-diary */
    color: #000000;
    background-color: #ffffff;
}
.org-org-agenda-dimmed-todo {
    /* org-agenda-dimmed-todo-face */
    color: #7f7f7f;
}
.org-org-agenda-done {
    /* org-agenda-done */
    color: #228b22;
}
.org-org-agenda-filter-category {
    /* org-agenda-filter-category */
    color: #000000;
    background-color: #bfbfbf;
}
.org-org-agenda-filter-effort {
    /* org-agenda-filter-effort */
    color: #000000;
    background-color: #bfbfbf;
}
.org-org-agenda-filter-regexp {
    /* org-agenda-filter-regexp */
    color: #000000;
    background-color: #bfbfbf;
}
.org-org-agenda-filter-tags {
    /* org-agenda-filter-tags */
    color: #000000;
    background-color: #bfbfbf;
}
.org-org-agenda-restriction-lock {
    /* org-agenda-restriction-lock */
    background-color: #eeeeee;
}
.org-org-agenda-structure {
    /* org-agenda-structure */
    color: #0000ff;
}
.org-org-agenda-structure-secondary {
    /* org-agenda-structure-secondary */
    color: #0000ff;
}
.org-org-archived {
    /* org-archived */
    color: #7f7f7f;
}
.org-org-block {
    /* org-block */
    color: #7f7f7f;
}
.org-org-block-begin-line {
    /* org-block-begin-line */
    color: #b22222;
}
.org-org-block-end-line {
    /* org-block-end-line */
    color: #b22222;
}
.org-org-checkbox {
    /* org-checkbox */
    font-weight: bold;
}
.org-org-checkbox-statistics-done {
    /* org-checkbox-statistics-done */
    color: #228b22;
    font-weight: bold;
}
.org-org-checkbox-statistics-todo {
    /* org-checkbox-statistics-todo */
    color: #ff0000;
    font-weight: bold;
}
.org-org-cite {
    /* org-cite */
    color: #3a5fcd;
    text-decoration: underline;
}
.org-org-cite-key {
    /* org-cite-key */
    color: #3a5fcd;
    text-decoration: underline;
}
.org-org-clock-overlay {
    /* org-clock-overlay */
    color: #000000;
    background-color: #d3d3d3;
}
.org-org-code {
    /* org-code */
    color: #7f7f7f;
}
.org-org-column {
    /* org-column */
    background-color: #e5e5e5;
}
.org-org-column-title {
    /* org-column-title */
    background-color: #e5e5e5;
    font-weight: bold;
    text-decoration: underline;
}
.org-org-date {
    /* org-date */
    color: #a020f0;
    text-decoration: underline;
}
.org-org-date-selected {
    /* org-date-selected */
    color: #ff0000;
}
.org-org-default {
    /* org-default */
    color: #000000;
    background-color: #ffffff;
}
.org-org-dispatcher-highlight {
    /* org-dispatcher-highlight */
    color: #00008b;
    background-color: #c6e2ff;
    font-weight: bold;
}
.org-org-document-info {
    /* org-document-info */
    color: #191970;
}
.org-org-document-info-keyword {
    /* org-document-info-keyword */
    color: #7f7f7f;
}
.org-org-document-title {
    /* org-document-title */
    color: #191970;
    font-weight: bold;
}
.org-org-done {
    /* org-done */
    color: #228b22;
    font-weight: bold;
}
.org-org-drawer {
    /* org-drawer */
    color: #0000ff;
}
.org-org-ellipsis {
    /* org-ellipsis */
    color: #b8860b;
    text-decoration: underline;
}
.org-org-footnote {
    /* org-footnote */
    color: #a020f0;
    text-decoration: underline;
}
.org-org-formula {
    /* org-formula */
    color: #b22222;
}
.org-org-headline-done {
    /* org-headline-done */
    color: #bc8f8f;
}
.org-org-headline-todo {
    /* org-headline-todo */
    color: #8b0000;
}
.org-org-hide {
    /* org-hide */
    color: #ffffff;
}
.org-org-imminent-deadline {
    /* org-imminent-deadline */
    color: #ff0000;
    font-weight: bold;
}
.org-org-inline-src-block {
    /* org-inline-src-block */
    color: #7f7f7f;
}
.org-org-latex-and-related {
    /* org-latex-and-related */
    color: #8b4513;
}
.org-org-level-1 {
    /* org-level-1 */
    color: #0000ff;
}
.org-org-level-2 {
    /* org-level-2 */
    color: #a0522d;
}
.org-org-level-3 {
    /* org-level-3 */
    color: #a020f0;
}
.org-org-level-4 {
    /* org-level-4 */
    color: #b22222;
}
.org-org-level-5 {
    /* org-level-5 */
    color: #228b22;
}
.org-org-level-6 {
    /* org-level-6 */
    color: #008b8b;
}
.org-org-level-7 {
    /* org-level-7 */
    color: #483d8b;
}
.org-org-level-8 {
    /* org-level-8 */
    color: #8b2252;
}
.org-org-link {
    /* org-link */
    color: #3a5fcd;
    text-decoration: underline;
}
.org-org-list-dt {
    /* org-list-dt */
    font-weight: bold;
}
.org-org-macro {
    /* org-macro */
    color: #8b4513;
}
.org-org-meta-line {
    /* org-meta-line */
    color: #b22222;
}
.org-org-mode-line-clock {
    /* org-mode-line-clock */
    color: #000000;
    background-color: #bfbfbf;
}
.org-org-mode-line-clock-overrun {
    /* org-mode-line-clock-overrun */
    color: #000000;
    background-color: #ff0000;
}
.org-org-priority {
    /* org-priority */
    color: #a020f0;
}
.org-org-property-value {
    /* org-property-value */
    color: #000000;
    background-color: #ffffff;
}
.org-org-quote {
    /* org-quote */
    color: #7f7f7f;
}
.org-org-scheduled {
    /* org-scheduled */
    color: #006400;
}
.org-org-scheduled-previously {
    /* org-scheduled-previously */
    color: #b22222;
}
.org-org-scheduled-today {
    /* org-scheduled-today */
    color: #006400;
}
.org-org-sexp-date {
    /* org-sexp-date */
    color: #a020f0;
}
.org-org-special-keyword {
    /* org-special-keyword */
    color: #a020f0;
}
.org-org-table {
    /* org-table */
    color: #0000ff;
}
.org-org-table-header {
    /* org-table-header */
    color: #000000;
    background-color: #d3d3d3;
}
.org-org-tag {
    /* org-tag */
    font-weight: bold;
}
.org-org-tag-group {
    /* org-tag-group */
    font-weight: bold;
}
.org-org-target {
    /* org-target */
    text-decoration: underline;
}
.org-org-time-grid {
    /* org-time-grid */
    color: #b8860b;
}
.org-org-todo {
    /* org-todo */
    color: #ff0000;
    font-weight: bold;
}
.org-org-upcoming-deadline {
    /* org-upcoming-deadline */
    color: #b22222;
}
.org-org-upcoming-distant-deadline {
    /* org-upcoming-distant-deadline */
    color: #000000;
    background-color: #ffffff;
}
.org-org-verbatim {
    /* org-verbatim */
    color: #7f7f7f;
}
.org-org-verse {
    /* org-verse */
    color: #7f7f7f;
}
.org-org-warning {
    /* org-warning */
    color: #ff0000;
    font-weight: bold;
}
.org-outline-1 {
    /* outline-1 */
    color: #0000ff;
}
.org-outline-2 {
    /* outline-2 */
    color: #a0522d;
}
.org-outline-3 {
    /* outline-3 */
    color: #a020f0;
}
.org-outline-4 {
    /* outline-4 */
    color: #b22222;
}
.org-outline-5 {
    /* outline-5 */
    color: #228b22;
}
.org-outline-6 {
    /* outline-6 */
    color: #008b8b;
}
.org-outline-7 {
    /* outline-7 */
    color: #483d8b;
}
.org-outline-8 {
    /* outline-8 */
    color: #8b2252;
}
.org-package-description {
    /* package-description */
    color: #000000;
    background-color: #ffffff;
}
.org-package-name {
    /* package-name */
    color: #3a5fcd;
    text-decoration: underline;
}
.org-package-status-avail-obso {
    /* package-status-avail-obso */
    color: #ff0000;
    font-weight: bold;
}
.org-package-status-available {
    /* package-status-available */
    color: #000000;
    background-color: #ffffff;
}
.org-package-status-built-in {
    /* package-status-built-in */
    color: #483d8b;
}
.org-package-status-dependency {
    /* package-status-dependency */
    color: #b22222;
}
.org-package-status-disabled {
    /* package-status-disabled */
    color: #ff0000;
    font-weight: bold;
}
.org-package-status-external {
    /* package-status-external */
    color: #483d8b;
}
.org-package-status-from-source {
}
.org-package-status-held {
    /* package-status-held */
    color: #008b8b;
}
.org-package-status-incompat {
    /* package-status-incompat */
    color: #ff0000;
    font-weight: bold;
}
.org-package-status-installed {
    /* package-status-installed */
    color: #b22222;
}
.org-package-status-unsigned {
    /* package-status-unsigned */
    color: #ff0000;
    font-weight: bold;
}
.org-preprocessor {
    /* font-lock-preprocessor-face */
    color: #483d8b;
}
.org-property-name {
    /* font-lock-property-name-face */
    color: #a0522d;
}
.org-property-use {
    /* font-lock-property-use-face */
    color: #a0522d;
}
.org-punctuation {
}
.org-query-replace {
    /* query-replace */
    color: #b0e2ff;
    background-color: #cd00cd;
}
.org-regexp {
    /* font-lock-regexp-face */
    color: #8b2252;
}
.org-regexp-grouping-backslash {
    /* font-lock-regexp-grouping-backslash */
    font-weight: bold;
}
.org-regexp-grouping-construct {
    /* font-lock-regexp-grouping-construct */
    font-weight: bold;
}
.org-region {
    /* region */
    background-color: #eedc82;
}
.org-scroll-bar {
}
.org-secondary-selection {
    /* secondary-selection */
    background-color: #ffff00;
}
.org-separator-line {
    /* separator-line */
    background-color: #a0a0a0;
    font-size: 10%;
}
.org-shadow {
    /* shadow */
    color: #7f7f7f;
}
.org-show-paren-match {
    /* show-paren-match */
    background-color: #40e0d0;
}
.org-show-paren-match-expression {
    /* show-paren-match-expression */
    background-color: #40e0d0;
}
.org-show-paren-mismatch {
    /* show-paren-mismatch */
    color: #ffffff;
    background-color: #a020f0;
}
.org-string {
    /* font-lock-string-face */
    color: #8b2252;
}
.org-success {
    /* success */
    color: #228b22;
    font-weight: bold;
}
.org-tab-bar {
    /* tab-bar */
    color: #000000;
    background-color: #d9d9d9;
}
.org-tab-bar-tab {
    /* tab-bar-tab */
    color: #000000;
    background-color: #d9d9d9;
}
.org-tab-bar-tab-group-current {
    /* tab-bar-tab-group-current */
    color: #000000;
    background-color: #d9d9d9;
    font-weight: bold;
}
.org-tab-bar-tab-inactive {
    /* tab-bar-tab-inactive */
    color: #000000;
    background-color: #bfbfbf;
}
.org-tab-line {
    /* tab-line */
    color: #000000;
    background-color: #d9d9d9;
    font-size: 90%;
}
.org-table-cell {
    /* table-cell */
    color: #e5e5e5;
    background-color: #0000ff;
}
.org-tabulated-list-fake-header {
    /* tabulated-list-fake-header */
    font-weight: bold;
    text-decoration: underline;
    text-decoration: overline;
}
.org-tool-bar {
    /* tool-bar */
    color: #000000;
    background-color: #bfbfbf;
}
.org-tooltip {
    /* tooltip */
    color: #000000;
    background-color: #ffffe0;
}
.org-trailing-whitespace {
    /* trailing-whitespace */
    background-color: #ff0000;
}
.org-tty-menu-disabled {
    /* tty-menu-disabled-face */
    color: #d3d3d3;
    background-color: #0000ff;
}
.org-tty-menu-enabled {
    /* tty-menu-enabled-face */
    color: #ffff00;
    background-color: #0000ff;
    font-weight: bold;
}
.org-tty-menu-selected {
    /* tty-menu-selected-face */
    background-color: #ff0000;
}
.org-type {
    /* font-lock-type-face */
    color: #228b22;
}
.org-underline {
    /* underline */
    text-decoration: underline;
}
.org-variable-name {
    /* font-lock-variable-name-face */
    color: #a0522d;
}
.org-variable-pitch {
}
.org-variable-pitch-text {
    /* variable-pitch-text */
    font-size: 100%;
}
.org-variable-use {
    /* font-lock-variable-use-face */
    color: #a0522d;
}
.org-vc-conflict-state {
}
.org-vc-edited-state {
}
.org-vc-locally-added-state {
}
.org-vc-locked-state {
}
.org-vc-missing-state {
}
.org-vc-needs-update-state {
}
.org-vc-removed-state {
}
.org-vc-state-base {
}
.org-vc-up-to-date-state {
}
.org-vertical-border {
}
.org-warning {
    /* warning */
    color: #ff8c00;
    font-weight: bold;
}
.org-warning-1 {
    /* font-lock-warning-face */
    color: #ff0000;
    font-weight: bold;
}
.org-window-divider {
    /* window-divider */
    color: #999999;
}
.org-window-divider-first-pixel {
    /* window-divider-first-pixel */
    color: #cccccc;
}
.org-window-divider-last-pixel {
    /* window-divider-last-pixel */
    color: #666666;
}</style>
#+end_export

#+begin_export html
</div>
#+end_export

** Declaring necessary variables and stuff for generation and org-publish
#+BEGIN_SRC emacs-lisp
  (defvar base-directory (expand-file-name "~/projects/website/"))
  (defvar public-directory (file-name-concat base-directory "public"))

  (setq org-html-head-include-default-style t
	org-html-preamble t
	org-html-htmlize-output-type 'css
	org-html-postamble t
	)
#+END_SRC

#+RESULTS:
: t



*** the ~org-publish-project-alist~ variable
At the heart of using ~org-publish~ is the ~org-publish-project-alist~ variable.

As the documentation of this variable specifies:
#+BEGIN_QUOTE
Association list to control publishing behavior.

Each element of the alist is a publishing project.  The car of
each element is a string, uniquely identifying the project.  The
cdr of each element is in one of the following forms:

1. A well-formed property list with an even number of elements,
   alternating keys and values, specifying parameters for the
   publishing process.

     (:property value :property value ... )

2. A meta-project definition, specifying of a list of
   sub-projects:

     (:components ("project-1" "project-2" ...))
#+END_QUOTE


#+BEGIN_SRC emacs-lisp :eval yes
  ;; in an effort to stop repeating myself that often
  (defvar posts-kw "posts")
  (defvar showcase-kw "projects")
  (defvar assets-kw "assets")

  (defvar public-assets-dir (file-name-concat public-directory "assets"))
  (defvar base-assets-dir (file-name-concat base-directory "assets"))

  (defvar public-posts-dir (file-name-concat public-directory "posts"))
  (defvar base-posts-dir (file-name-concat base-directory "posts"))

  (defvar public-showcase-dir (file-name-concat public-posts-dir "showcase"))
  (defvar base-showcase-dir (file-name-concat base-posts-dir "showcase"))

  (setq org-publish-project-alist
	`(
	  ("assets"
	   :base-directory ,base-assets-dir
	   :base-extension "css\\|js\\|png\\|jpg\\|jpeg\\|gif\\|pdf\\|mp3\\|ogg\\|swf"
	   :publishing-directory ,public-assets-dir
	   :recursive t
	   :publishing-function org-publish-attachment)
	  ("posts"
	   :base-directory ,base-posts-dir
	   :inline-components ("assets")
	   :base-extension "org"
	   :publishing-directory ,public-posts-dir
	   :publishing-function org-html-publish-to-html
	   ;; :html-preamble "<link rel='stylesheet' type='text/css' href='../assets/style.css'/>"
	   :html-postamble ,(concat
			     "<p class=\"author\">%a</p>"
			     "<p class=\"author\">Date: %T</p>"
			     "<p class=\"author\">%c</p>")
	   :headline-levels 4
	   :auto-preamble t)
	  ("showcase"
	   :base-directory ,base-showcase-dir
	   :base-extension "org"
	   :publishing-directory ,public-showcase-dir
	   :publishing-function org-html-publish-to-html
	   ;; :html-preamble "<link rel='stylesheet' type='text/css' href='../../assets/style.css'/>"
	   )
	  ("index"
	   :base-directory ,base-directory
	   :inline-components ("posts" "showcase")
	   :publishing-directory ,public-directory
	   :publishing-function org-html-publish-to-html
	   ;; :html-preamble "<link rel='stylesheet' type='text/css' href='assets/style.css'/>"
	   )
	  ("website" :components ("assets" "posts" "showcase" "index"))))
#+END_SRC

#+RESULTS:
| assets   | :base-directory | /home/ik/projects/website/assets         | :base-extension    | css\             | js\                   | png\                                            | jpg\                  | jpeg\                                  | gif\                 | pdf\                     | mp3\            | ogg\                                                                           | swf              | :publishing-directory | /home/ik/projects/website/public/assets | :recursive | t | :publishing-function | org-publish-attachment |
| posts    | :base-directory | /home/ik/projects/website/posts          | :inline-components | (assets)         | :base-extension       | org                                             | :publishing-directory | /home/ik/projects/website/public/posts | :publishing-function | org-html-publish-to-html | :html-postamble | <p class="author">%a</p><p class="author">Date: %T</p><p class="author">%c</p> | :headline-levels |                     4 | :auto-preamble                          | t          |   |                      |                        |
| showcase | :base-directory | /home/ik/projects/website/posts/showcase | :base-extension    | org              | :publishing-directory | /home/ik/projects/website/public/posts/showcase | :publishing-function  | org-html-publish-to-html               |                      |                          |                 |                                                                                |                  |                       |                                         |            |   |                      |                        |
| index    | :base-directory | /home/ik/projects/website/               | :inline-components | (posts showcase) | :publishing-directory | /home/ik/projects/website/public                | :publishing-function  | org-html-publish-to-html               |                      |                          |                 |                                                                                |                  |                       |                                         |            |   |                      |                        |
| website  | :components     | (assets posts showcase index)            |                    |                  |                       |                                                 |                       |                                        |                      |                          |                 |                                                                                |                  |                       |                                         |            |   |                      |                        |

** Actual generating the files
Everything prior has been setting up the necessary pieces of what things go where, and how.

Like setting up a railway track from one point to another.

Now that all that has been specified, we can finally run a train across the track, generating our files.

Since this process utilises ~org-publish~, which does a lot of the heavy lifting, this part is small.

#+BEGIN_SRC emacs-lisp
  (org-publish "website" t) ;; :)
#+END_SRC

#+RESULTS:

Yeah... that's it.

** Pushing to the remote repo for deployment
I'm not exactly sure how I am going to plug this functionality into
emacs, I know its absolutely possible.

It might be a little overkill, as the process of staging, commiting
and pushing to GitHub is atmost three lines in the command line.

But we've come so far, might as well have emacs cross the finish line
themselves, it shouldn't be too hard. Right?...

That's a job for a future me
 
---

You can find this exact file (in it's ~org-mode~ state) [[https://github.com/ismaelkdev/website/blob/main/index.org][here]], where
you can use it to perhaps jumpstart your own webpage. Apart from the
project structure, stylesheet, and the individual blog posts (atm)
this entire webpage is self-sustained in this single file.

** Exporting posts to their own html files
Though this is a "mono-page" (all posts are actually present in this
page); it would be worthwhile to have each post be accessible as their
own page, for I think, two particular reasons:
1. Sharing individual posts without overwhelming
2. Better "SEO" with the individual pages

The way I think I will approach this is by collecting the positions of
each level 1 org header, checking if they are valid to be exported as
its own post page (perhaps by a property tag, or simply by checking if
it *doesnt* have a tag that says something like "noexport" or
something.

Though these need to maintain the stylesheet, I'll figure out a way
to ensure that these pages get generated with the same style sheet
provided here, so things remain consistent across pages.

#+BEGIN_SRC emacs-lisp 
    (defun extract-html-from-results (results-name)
      "Extract the HTML contents of a #+RESULTS block named RESULTS-NAME in an Org buffer."
      (save-excursion
	(goto-char (point-min))
	(if (re-search-forward (format "#\\+RESULTS: %s" results-name) nil t)
	    (let ((start (progn
			   (re-search-forward "#\\+BEGIN_EXPORT html" nil t)
			   (point)))
		  (end (progn
			 (re-search-forward "#\\+END_EXPORT" nil t)
			 (match-beginning 0))))
	      (buffer-substring-no-properties start end))
	  (error "No RESULTS block named %s found" results-name))))

    (defun remove-narrowed-page-links ()
      "Find and remove all links of the format [[<path-to-file>][Link to narrowed page]] from the buffer.
       This particular function's primary use is to make sure that the 'Link to narrowed pages' "
      (save-excursion
	(goto-char (point-min))
	(while (re-search-forward "\\[\\[.*?\\]\\[Link to narrowed page\\]\\]" nil t)
	  (replace-match ""))))

    (defun produce-html-posts-subpages (filename output-dir)
      "Iterate through each of the level 1 headers of the org file, and
       produce HTML files of each one, despite it being a mono-page, having
       actual html files allows the user to narrow down the webpage, and might
       also help with SEO."
      (setq website-stylesheet (extract-html-from-results "stylesheet"))
      ;; things are getting a little inconsistent, but I'm just getting my
      ;; bearings and tinkering.
      (with-temp-buffer
	(insert-file-contents filename)
	(org-mode)
	(org-element-map (org-element-parse-buffer) 'headline
	  (lambda (hl)
	    (when (and
		   (= (org-element-property :level hl) 1)
		   (not (org-element-property :NO_DEDICATED_PAGE hl))
		   )
	      (let* ((title (org-element-property :raw-value hl))
		     (slug (downcase (replace-regexp-in-string "[^a-z0-9]+" "-" title)))
		     (output-fname (file-name-concat output-dir
						     (concat slug ".html")))

		     (hl-content-begin (org-element-property :begin hl))
		     (content (progn
				(goto-char hl-content-begin)
				(org-export-as 'org t nil t))))
		;; BODY of let*
		(with-temp-file output-fname
		  (insert content)
		  ;; eventually, this will be a HTML file, but we can
		  ;; start by treating it as an org file, making our tweaks
		  ;; and then using org-export to get the document as html,
		  ;; and replace all of its contents with that.
		  (org-mode)
		  ;; add some stuff like the title
		  (goto-char 0) ;; go to start of the file.
		  (insert (concat "#+TITLE: " title "\n"
				  "#+options: toc:nil \n"
				  "[[../index.org][Link back home]]\n\n"))

		  (remove-narrowed-page-links)

		  (let ((html-content (org-export-as 'html nil nil nil)))
		    (erase-buffer)
		    (insert website-stylesheet)
		    (insert html-content)
		    ) 
		  )
		))))))
#+END_SRC

#+RESULTS:
: produce-html-posts-subpages

And so, I've kinda bypassed ~org-publish~ here, but this produces
~.html~ files under ~/posts~ whose filenames are the same as the post
name, but "slug'ified", and with a link back to the home mono-page.

Below actually executes the function and puts things in the right spot:

#+BEGIN_SRC elisp
(produce-html-posts-subpages "index.org" "public/posts")
#+END_SRC

#+RESULTS:

** Accessing the narrowed subpages from the mono-page
# ---
